### ISSUE TITLE
Support missing features

### ISSUE THREAD

**Issue by shoriwe** [Finnhub-Stock-API/finnhub-go#12]
Support missing API routes

- [x] `/stock/price-metric`
- [x] `/stock/earnings`

**Comment by shoriwe** [comment]
## `/stock/earnings`

`Earnings Surprises` is the equivalent to `Company Earnings`, this feature was already implemented but the Go API is probably using an outdated name for the symbol

This feature is already implemented but using the name `CompanyEarnings`. Example:

```go
client.DefaultApi.CompanyEarnings(context.Background()).Symbol(symbol).Execute()
```

**Comment by finnhubio** [comment]
This should be added in the latest release now.
