### ISSUE TITLE
CompanyBasicFinancials throws an error of undefined response type

### ISSUE THREAD

**Issue by obitech** [Finnhub-Stock-API/finnhub-go#2]
Hey,

the client library (`v1.1.2`) fails when retrieving basic financial information:

```go
	metrics, _, err := client.CompanyBasicFinancials(ctx, "AAPL", "all")
	if err != nil {
		fmt.Printf("error: %v",err)
	}

	fmt.Println(metrics)
```

Will print:

```
error: undefined response type
```

**Comment by nongdenchet** [comment]
thank you for reporting we are on it 👍

**Comment by finnhubio** [comment]
The issue should be fixed now.

**Comment by nongdenchet** [comment]
I am closing this, feel free to reopen if you still encounter the issue

**Comment by obitech** [comment]
I've tested it and it works now, thanks a lot guys! :tada:
